### ISSUE TITLE
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'

### ISSUE THREAD

**Issue by felicityfmn** [oneclick/rubyinstaller2#96] opened 2018-01-30 09:41 UTC
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
I keep getting this error message on the console even though I have the event machine gem installed and the require em/pure_ruby

## What's the output from `ridk version`?
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- 2.4/rubyeventmachine (LoadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:10:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby24-x64/flutterbot/play.rb:3:in `<main>'

**Comment by larskanis** [comment] 2018-01-30 10:27
Although eventmachine is provided as `x64-mingw` platform gem, it doesn't support ruby-2.4 or 2.5 right now. So would recommend you to do the following:

1. Open an issue at eventmachine to update [their dependency to rake-compiler-dock-0.6](https://github.com/eventmachine/eventmachine/blob/master/eventmachine.gemspec#L23) and to add ruby-2.4 and 2.5 binary support this way and ask them for a new x64-mingw release.
2. Ask the people at eventmachine, how 'em/pure_ruby' is supposed to work.
3. Use `gem install eventmachine --platform ruby` in the meantime.

**Comment by larskanis** [comment] 2018-02-24 22:11
This issue is forwarded to eventmachine [here](https://github.com/eventmachine/eventmachine/issues/820). Closing now. Thank you @felicityfmn !

**Closed by larskanis** 2018-02-24 22:11 UTC

**Comment by IsaiaSilva** [comment] 2018-09-14 04:17
This problem always occurs ... No convincing answer yet

**Comment by Impeck** [comment] 2018-10-24 12:08
gem uninstall eventmachine
gem install eventmachine --platform ruby

**Comment by Impeck** [comment] 2018-10-31 09:33
To solve the problem specified in the topic you need to run these commands:
```
gem uninstall eventmachine
gem install eventmachine --platform ruby
```

**Comment by khiav223577** [comment] 2019-10-31 07:38
I have to check whether `EventMachine` is defined before `require em/pure_ruby` to prevent getting warnings.
```rb
require 'em/pure_ruby' if not defined?(EventMachine)
```

**Comment by EglomSostenes** [comment] 2020-01-24 23:49
> To solve the problem specified in the topic you need to run these commands:
> 
> ```
> gem uninstall eventmachine
> gem install eventmachine --platform ruby
> ```

Para os BRs: "Resolveu o meu problema"

**Comment by pke** [comment] 2020-05-07 00:26
> ```ruby
> require 'em/pure_ruby' if not defined?(EventMachine)
> ```

Where did you put this code?

**Comment by khiav223577** [comment] 2020-05-07 09:23
> > ```ruby
> > require 'em/pure_ruby' if not defined?(EventMachine)
> > ```
> 
> Where did you put this code @khiav223577?

@pke 
I put it at the first line of `config/boot.rb` in the beginning.

But I use this patch currently:
```rb
# config/patch_eventmachine.rb
class Bundler::Runtime
  alias_method :require_without_patching_eventmachine, :require

  def require(*groups)
    begin
      require_without_patching_eventmachine(*groups)
    rescue LoadError => e
      if e.path == '2.5/rubyeventmachine' # when require '2.5/rubyeventmachine' fails
        super 'em/pure_ruby'
        retry
      end

      raise e
    end
  end
end
```
```rb
# config/boot.rb
require_relative 'patch_eventmachine'

...
...
```

**Comment by pke** [comment] 2020-05-09 00:35
I am having this problem when using `bundle exec jekyll s`. Where would I apply your patch then?

**Comment by khiav223577** [comment] 2020-05-09 07:37
> I am having this problem when using `bundle exec jekyll s`. Where would I apply your patch then?

I know nothing about `jekyll`.
You could submit an issue on [jekyll](https://github.com/jekyll/jekyll) to ask for help.

**Comment by Neha5248** [comment] 2020-08-24 15:13
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
cannot load such file -- 2.6/rubyeventmachine (LoadError)
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faye-websocket-0.11.0/lib/faye/websocket.rb:10:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.11.0/lib/appium_lib_core/common/ws/websocket.rb:15:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.11.0/lib/appium_lib_core/common.rb:21:in `require_relative'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.11.0/lib/appium_lib_core/common.rb:21:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.11.0/lib/appium_lib_core.rb:18:in `require_relative'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.11.0/lib/appium_lib_core.rb:18:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib-10.6.0/lib/appium_lib/appium.rb:19:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib-10.6.0/lib/appium_lib.rb:24:in `require_relative'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/appium_lib-10.6.0/lib/appium_lib.rb:24:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
C:/Users/Neha/Desktop/automation_appium/features/support/env.rb:3:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-5.1.0/lib/cucumber/glue/registry_and_more.rb:121:in `load_code_file'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-5.1.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-5.1.0/lib/cucumber/runtime/support_code.rb:81:in `block in load_files!'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-5.1.0/lib/cucumber/runtime/support_code.rb:80:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-5.1.0/lib/cucumber/runtime/support_code.rb:80:in `load_files!'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-5.1.0/lib/cucumber/runtime.rb:255:in `load_step_definitions'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-5.1.0/lib/cucumber/runtime.rb:72:in `run!'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-5.1.0/lib/cucumber/cli/main.rb:29:in `execute!'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cucumber-5.1.0/bin/cucumber:9:in `<top (required)>'
C:/Ruby26-x64/bin/cucumber:23:in `load'
C:/Ruby26-x64/bin/cucumber:23:in `<main>'
![Ruby](https://user-images.githubusercontent.com/13568810/91062556-7dc12600-e64a-11ea-8c03-28bc785bcc4c.PNG)

**Comment by MSP-Greg** [comment] 2020-08-24 15:44
@Neha5248

Try:
```
gem uninstall eventmachine
ridk exec pacman -Sy openssl
gem install eventmachine --platform=ruby
```

`ridk exec pacman -Sy openssl` updates MSYS2 and installs the MSYS2 openssl package.  This may take a little while...

`gem install eventmachine --platform=ruby` installs EventMachine but forces compiling the gem

EventMachine's current x64-mingw32 gem is not compatible with Ruby 2.6 and later, and it was accidentally built without that information in the gemspec.

**Comment by Neha5248** [comment] 2020-08-24 16:02
@MSP-Greg  

Thank a lot it's working fine now :)

**Comment by reach2jeyan** [comment] 2020-08-25 09:19
If you are using windows

Go to this folder `C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\eventmachine-1.2.5-x64-mingw32\lib`

open this file `eventmachine.rb`

write this require `'em/pure_ruby'` in the first line of code in the file
this will make it work with no issues.

**Comment by makubex88** [comment] 2020-10-03 20:25
> gem uninstall eventmachine
> gem install eventmachine --platform ruby

this works on my end.

**Comment by vincerubinetti** [comment] 2021-04-18 19:01
For those running into this problem with Jekyll's live-reload (`bundle exec jekyll serve --livereload`), I had to combine several of the above solutions to get it to (almost) work for me:

1. Completely uninstall Ruby and MSYS2
2. Install Ruby and MSYS2 with [Ruby Installer Ruby+Devkit 2.7.2-1 (x64)](https://rubyinstaller.org/downloads/)
3. `gem uninstall eventmachine` and choose all to uninstall
4. `gem install eventmachine --platform ruby`
5. Open `C:\Ruby24-x64\lib\ruby\gems\{version of ruby}\gems\eventmachine-1.2.5-x64-mingw32\lib\eventmachine.rb`
6. Insert `require 'em/pure_ruby' if not defined?(EventMachine)` at the top of the file

This makes it work for me, though the process still seems to crash randomly sometimes. Really wish this issue was fixed... upstream or wherever the problem lies.

**Comment by SeaDude** [comment] 2021-06-12 03:04
> Although eventmachine is provided as `x64-mingw` platform gem, it doesn't support ruby-2.4 or 2.5 right now. So would recommend you to do the following:
> 
> 1. Open an issue at eventmachine to update [their dependency to rake-compiler-dock-0.6](https://github.com/eventmachine/eventmachine/blob/master/eventmachine.gemspec#L23) and to add ruby-2.4 and 2.5 binary support this way and ask them for a new x64-mingw release.
> 2. Ask the people at eventmachine, how 'em/pure_ruby' is supposed to work.
> 3. Use `gem install eventmachine --platform ruby` in the meantime.

Interesting that this is still required a few years later. 

- Fresh install on Windows 10 following official Quickstart docs
- Running:
`jekyll new eblog`
`cd eblog`
`bundle exec jekyll serve`
- Fails with: 
```
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
```
- Ran `bundle add webrick`
- Then `bundle exec jekyll serve`
- Fails with:
```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `require': cannot load such file -- 3.0/rubyeventmachine (LoadError)
```
- Tried running `bundle add rubyeventmachine`
```
Could not find gem 'rubyeventmachine' in rubygems repository
https://rubygems.org/ or installed locally.
The source does not contain any versions of 'rubyeventmachine'
```
- Found this Github issue and ran `gem install eventmachine --platform ruby`
- Now `bundle exec jekyll serve` serves up the website as intended.

**Comment by RobTranquillo** [comment] 2021-08-11 06:59
This one did not quite work

>     3. `gem uninstall eventmachine` and choose all to uninstall
> 
>     4. `ridk exec pacman -Sy openssl` (run in Command Prompt, not Git Bash or some other shell)
> 
>     5. `gem install eventmachine --platform ruby`

But with the install command from eventmachine website it does!

`gem install eventmachine -v 1.2.7`

1. `gem uninstall eventmachine` and choose all to uninstall
2. `ridk exec pacman -Sy openssl` (run in Command Prompt, not Git Bash or some other shell)
3. `gem install eventmachine -v 1.2.7`

**Comment by spaquet** [comment] 2021-12-19 21:49
What worked for me on Apple Silicon M1 and Rails 6.1
* Full uninstall of eventmachine: `gem uninstall -aIx eventmachine` followed by a `rm -rf vendor/cache`
* Add eventmachine in the project Gemfile and forcing it to be from the master branch latest like this `gem 'eventmachine', :git => 'git://github.com/eventmachine/eventmachine.git', :branch => 'master'`
* Run `bundle install`

**Comment by Lojlk** [comment] 2022-01-01 07:34
> @Neha5248
> 
> For Ruby 2.5 and later, try:
> 
> ```
> gem uninstall eventmachine
> ridk exec pacman -Sy openssl
> gem install eventmachine --platform=ruby
> ```
> 
> `ridk exec pacman -Sy openssl` updates MSYS2 and installs the MSYS2 openssl package. This may take a little while...
> 
> `gem install eventmachine --platform=ruby` installs EventMachine but forces compiling the gem
> 
> EventMachine's current x64-mingw32 gem is not compatible with Ruby 2.6 and later, and it was accidentally built without that information in the gemspec.
> 
> Ruby 2.5 and later use OpenSSL 1.1.1. Ruby 2.4 uses OpenSSL 1.0.2, which requires a different set of commands.

Hi Greg, I followed your steps (am using Ruby 2.7.5) and "bundle exec jekyll serve --livereload" was met with Could not find eventmachine-1.2.7-x64-mingw32 in any of the sources. Any solutions? Thanks

**Comment by FredyRosero** [comment] 2022-01-30 19:07
I had that error when I run `bundle exec jekyll serve --livereload --trace` on Jekyll.4.2.1-Ruby.3.0.3p137(mingw)-Windows. I ran `gem install eventmachine --platform=ruby` and it compiled at `C:\Ruby30-x64\lib\ruby\gems\3.0.0\gems\eventmachine-1.2.7` but when you run `bundle install` it creates also `C:\Ruby30-x64\lib\ruby\gems\3.0.0\gems\eventmachine-1.2.7-x64-mingw32` 🤔. The command `bundle info eventmachine` gives me `C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7-x64-mingw32` and that's confimed in the Gemfile.lock with the line `eventmachine (1.2.7-x64-mingw32)`. So I changed that line for `eventmachine (1.2.7)` and then the output of `bundle info eventmachine` gives me `C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7` and finally the command `bundle exec jekyll serve --livereload --trace` worked ✔️
