### ISSUE TITLE
can't open C:\Users\��\AppData\Local\Temp\cc4K9XbU.s for reading: Illegal byte sequence make: *** [Makefile:247: c99func.o]

### ISSUE THREAD

**Issue by yunkyukim** [oneclick/rubyinstaller2#320] opened 2022-12-11 08:06 UTC
## What problems are you experiencing?
can't open C:\Users\��\AppData\Local\Temp\cc4K9XbU.s for reading: Illegal byte sequence
make: *** [Makefile:247: c99func.o]

## What's the output from `ridk version`?
ruby:
  path: C:/Ruby31-x64
  version: 3.1.3
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.3-1
  git_commit: a09714d
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev6, Built by MSYS2 project) 12.2.0
sh: GNU bash, 버전 5.2.9(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19044.2251]

**Comment by larskanis** [comment] 2022-12-11 10:30
Can you explain, what you're trying to do?

**Comment by yunkyukim** [comment] 2022-12-12 11:59
I'm trying to make my github.io using jekyll-theme-chirpy.

**Comment by yunkyukim** [comment] 2022-12-14 12:30
I put the same command: gem inst jekyll, but the results are same. Thanks for help anyway! I think I should read the manual carefully and try again...

**Comment by larskanis** [comment] 2022-12-14 14:25
Could it be that the username you're using consists of an invalid byte sequence? The error message looks like that. You might try an ASCII only name instead.

**Comment by mohits** [comment] 2022-12-14 15:50
@larskanis - I wonder if this is related to this earlier issue: https://github.com/oneclick/rubyinstaller2/issues/265

**Comment by kubo** [comment] 2022-12-15 10:11
@yunkyukim Could you post command output as @larskanis requested at https://github.com/oneclick/rubyinstaller2/issues/320#issuecomment-1346575158? Copy whole command output, not only the error lines, and past it in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks). The location of the error may be a hint to resolve this.

By the way, it may be fixed by changing `TMP` and `TEMP` environment variables as follows. The default value of them is `C:\Users\%USERNAME%\AppData\Local\Temp` and `cc4K9XbU.s` looks a temporary file created in the temporary directory specified by `TMP` or `TEMP`. I guess that it is fixed when either `TMP` or `TEMP` doesn't contain non-ASCII characters.

```
mkdir c:\temp
set TMP=c:\temp
set TEMP=c:\temp
gem inst jekyll --no-doc
```

**Comment by yunkyukim** [comment] 2022-12-16 13:02
@kubo I think my username is in Korean so I guess it is the reason.
Here's the whole command:

'''
C:\Users\나>gem inst jekyll --no-doc
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 extconf.rb
creating Makefile

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\= sitearchdir\=./.gem.20221216-11260-zbad8z sitelibdir\=./.gem.20221216-11260-zbad8z clean
bash.exe: warning: could not find /tmp, please create!

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\= sitearchdir\=./.gem.20221216-11260-zbad8z sitelibdir\=./.gem.20221216-11260-zbad8z
compiling ./libsass/src/ast.cpp
compiling ./libsass/src/ast2c.cpp
compiling ./libsass/src/ast_fwd_decl.cpp
compiling ./libsass/src/ast_sel_cmp.cpp
compiling ./libsass/src/ast_sel_super.cpp
compiling ./libsass/src/ast_sel_unify.cpp
compiling ./libsass/src/ast_sel_weave.cpp
compiling ./libsass/src/ast_selectors.cpp
compiling ./libsass/src/ast_supports.cpp
compiling ./libsass/src/ast_values.cpp
compiling ./libsass/src/backtrace.cpp
compiling ./libsass/src/base64vlq.cpp
compiling ./libsass/src/bind.cpp
compiling ./libsass/src/c2ast.cpp
compiling ./libsass/src/c99func.c
Assembler messages:
Error: can't open C:\Users\��\AppData\Local\Temp\ccGeDH5w.s for reading: Illegal byte sequence
make: *** [Makefile:247: c99func.o] 오류 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0 for inspection.
Results logged to C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/sassc-2.4.0/gem_make.out
'''

**Comment by yunkyukim** [comment] 2022-12-16 13:03
@kubo I think my username is in Korean so I guess it is the reason.
Here's the whole command:

```
C:\Users\나>gem inst jekyll --no-doc
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 extconf.rb
creating Makefile

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\= sitearchdir\=./.gem.20221216-11260-zbad8z sitelibdir\=./.gem.20221216-11260-zbad8z clean
bash.exe: warning: could not find /tmp, please create!

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\= sitearchdir\=./.gem.20221216-11260-zbad8z sitelibdir\=./.gem.20221216-11260-zbad8z
compiling ./libsass/src/ast.cpp
compiling ./libsass/src/ast2c.cpp
compiling ./libsass/src/ast_fwd_decl.cpp
compiling ./libsass/src/ast_sel_cmp.cpp
compiling ./libsass/src/ast_sel_super.cpp
compiling ./libsass/src/ast_sel_unify.cpp
compiling ./libsass/src/ast_sel_weave.cpp
compiling ./libsass/src/ast_selectors.cpp
compiling ./libsass/src/ast_supports.cpp
compiling ./libsass/src/ast_values.cpp
compiling ./libsass/src/backtrace.cpp
compiling ./libsass/src/base64vlq.cpp
compiling ./libsass/src/bind.cpp
compiling ./libsass/src/c2ast.cpp
compiling ./libsass/src/c99func.c
Assembler messages:
Error: can't open C:\Users\��\AppData\Local\Temp\ccGeDH5w.s for reading: Illegal byte sequence
make: *** [Makefile:247: c99func.o] 오류 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0 for inspection.
Results logged to C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/sassc-2.4.0/gem_make.out
```

**Comment by kubo** [comment] 2022-12-16 14:29
@yunkyukim 
Could you create a directory `c:\temp` and set `TMP=c:\temp` as described in https://github.com/oneclick/rubyinstaller2/issues/320#issuecomment-1352835306?

I reproduced this issue by setting `TMP=c:\いろは` on Japanese version of Windows as follows. I guess that this can be reproduced by setting a non-ASCII path to `TMP` on other language versions.

```
C:\ruby\rubyinstaller-3.1.0-1-x64\bin>mkdir c:\いろは

C:\ruby\rubyinstaller-3.1.0-1-x64\bin>set TMP=c:\いろは

C:\ruby\rubyinstaller-3.1.0-1-x64\bin>gem install sassc
Fetching sassc-2.4.0.gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing sassc:
        ERROR: Failed to build gem native extension.

    current directory: C:/ruby/rubyinstaller-3.1.0-1-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
C:/ruby/rubyinstaller-3.1.0-1-x64/bin/ruby.exe -I C:/ruby/rubyinstaller-3.1.0-1-x64/lib/ruby/3.1.0 -r ./siteconf20221216-14020-qhey2.rb extconf.rb
creating Makefile

current directory: C:/ruby/rubyinstaller-3.1.0-1-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\= clean

current directory: C:/ruby/rubyinstaller-3.1.0-1-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\=
compiling ./libsass/src/ast.cpp
compiling ./libsass/src/ast2c.cpp
compiling ./libsass/src/ast_fwd_decl.cpp
compiling ./libsass/src/ast_sel_cmp.cpp
compiling ./libsass/src/ast_sel_super.cpp
compiling ./libsass/src/ast_sel_unify.cpp
compiling ./libsass/src/ast_sel_weave.cpp
compiling ./libsass/src/ast_selectors.cpp
compiling ./libsass/src/ast_supports.cpp
compiling ./libsass/src/ast_values.cpp
compiling ./libsass/src/backtrace.cpp
compiling ./libsass/src/base64vlq.cpp
compiling ./libsass/src/bind.cpp
compiling ./libsass/src/c2ast.cpp
compiling ./libsass/src/c99func.c
Assembler messages:
Error: can't open c:\�����\ccaKD7kF.s for reading: Illegal byte sequence
make: *** [Makefile:246: c99func.o] エラー 1

make failed, exit code 2

Gem files will remain installed in C:/ruby/rubyinstaller-3.1.0-1-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0 for inspection.
Results logged to C:/ruby/rubyinstaller-3.1.0-1-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/sassc-2.4.0/gem_make.out
```

**Comment by larskanis** [comment] 2022-12-16 17:17
Thank you @kubo ! I can reproduce the issue as well by setting `TMP` to a unicode path. The issue is in `gcc` which seems to not use Unicode WINAPI. One can work around by setting the gcc options like so:

```diff
diff --git a/lib/ruby/3.1.0/x64-mingw-ucrt/rbconfig.rb b/lib/ruby/3.1.0/x64-mingw-ucrt/rbconfig.rb
index d82a209..4828a08 100644
--- a/lib/ruby/3.1.0/x64-mingw-ucrt/rbconfig.rb
+++ b/lib/ruby/3.1.0/x64-mingw-ucrt/rbconfig.rb
@@ -174,8 +174,8 @@ module RbConfig
   CONFIG["CXXFLAGS"] = "-march=nocona -msahf -mtune=generic -O2 -pipe"
   CONFIG["OBJEXT"] = "o"
   CONFIG["CPPFLAGS"] = "-D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0600 -D__MINGW_USE_VC2005_COMPAT $(DEFS) $(cppflags)"
-  CONFIG["LDFLAGS"] = "-L. -pipe -s -fstack-protector-strong -Wl,--no-as-needed"
-  CONFIG["CFLAGS"] = "-O3 -fno-fast-math -fstack-protector-strong"
+  CONFIG["LDFLAGS"] = "-L. -pipe -save-temps -s -fstack-protector-strong -Wl,--no-as-needed"
+  CONFIG["CFLAGS"] = "-O3 -pipe -fno-fast-math -fstack-protector-strong"
   CONFIG["STRIP"] = "strip -S -x"
   CONFIG["RANLIB"] = "x86_64-w64-mingw32-gcc-ranlib"
   CONFIG["OBJDUMP"] = "objdump"
```

I wonder if we should enable these options by default in RubyInstaller. `-pipe` is save to be used on Windows and fixes the issue for `*.c` files when invoking the assembler. `-pipe` is already enabled for `*.cpp`. So this is a no-brainer. I'm uncertain if [`-save-temps`](https://gcc.gnu.org/onlinedocs/gcc/Developer-Options.html#index-save-temps) could have a negative impact. Any idea?

**Closed** 2022-12-20 14:03 UTC

**Comment by kubo** [comment] 2022-12-22 05:43
This is just information. I'm not against the fix.

In https://github.com/oneclick/rubyinstaller2/commit/aa15f1a243ee20c109ce85e6d1573982ebb1bd36

> cmd and powershell mechanism to set variables doesn't support Unicode either.

cmd in Japanese version of Windows supports non-Unicode characters as long as they are in [CP932] (ANSI and OEM code page in Japanese version). I bet that `c:\いろは` in Japanese version and `C:\Users\나\AppData\Local\Temp` in Korean version cause no problems if `gcc` uses ANSI API in all places and treats byte sequence got by ANSI API as it is. The problem is that `gcc` supports unicode partly and decodes byte sequence of ANSI code page as UTF-8.

In order to check it, I set `TMP=c:\ﾂｱ` on Japanese version and got the error message: "No such file or directory" instead of "Illegal byte sequence".

```
Error: can't open c:\±\ccKrzIwR.s for reading: No such file or directory
```

The byte sequence of `c:\ﾂｱ` in CP932 is `63 3A 5C C2 B1`, which is also byte sequence of `c:\±` in UTF-8. So the error message "Illegal byte sequence" disappears.

character | byte sequence in cp932 | byte sequence in utf-8
---|---|---
`c` | `63` | `63`
`:` | `3A` | `3A`
`\` | `5C` | `5C`
`ﾂ` | `C2` | `EF BE 82` 
`ｱ` | `B1` | `EF BD B1`
`±` |  `81 7D` | `C2 B1`

[CP932]: https://en.wikipedia.org/wiki/Code_page_932_(Microsoft_Windows)
