### ISSUE TITLE
WIN10 claims 2.4.4-2 installer has Vigdorf.A trojan and won't install

### ISSUE THREAD

**Issue by GrahamDJones** [oneclick/rubyinstaller2#120] opened 2018-06-26 18:58 UTC
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).
applies to both with and without devkit

## What problems are you experiencing?
Download fails with generic message (download fails).
Turn off windows defender, try again, get installer exe.
Run exe, get installer has Vigdorf.A trojan and will not install

## Steps to reproduce
a) download file with windows defender turned on
b) download file with defender turned off, and run file on completeion

## What's the output from `ridk version`?
Did not get that far

**Comment by dzenifr** [comment] 2018-06-27 16:38
Win10 / Chrome will not finish download. 
Tried Brave browser, download will complete. 
Turned off WinDefender, SmartScreen won't allow install and Win10 actively deletes file from download location. 
Turned off SmartScreen, reboot, download exe, run exe is allowed, installation succeeds.

**Comment by GrahamDJones** [comment] 2018-06-27 18:06
dzenifr had the answer. Thank you. installation succeeded.

**Comment by brunoyb** [comment] 2018-06-27 18:35
I had a similar issue when trying to update using chocolatey (https://chocolatey.org/packages/ruby).

Installer used: https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.5.1-2/rubyinstaller-devkit-2.5.1-2-x64.exe

I would prefer if it worked without having to mess with SmartScreen.

Windows Version: 10.0.17134 Build 17134

**Comment by larskanis** [comment] 2018-06-27 18:55
I can reproduce the issue after another update of the defender signatures. Only Ruby-Devkit-2.5.1-2-x64 and Ruby-Devkit-2.4.4-2-x64 seems to be affected. But these are the most downloaded versions.

> I would prefer if it worked without having to mess with Windows Defender or SmartScreen.

Sure, I'll investigate it further.

**Comment by alaurie** [comment] 2018-06-28 02:57
Same thing here. All available Win10 updates installed. Had to exclude download directory from defender to be able to download and install.

![image](https://user-images.githubusercontent.com/1402140/42010581-b6a0702e-7ad2-11e8-8a46-229e5618b607.png)

**Comment by larskanis** [comment] 2018-06-29 18:46
I submitted `rubyinstaller-devkit-2.5.1-2-x64.exe` to [Microsoft for analysis](https://www.microsoft.com/en-us/wdsi/filesubmission). The automatic scan of the uploaded file didn't detect any malware. Unfortunately the submission details are private, so that I can't link to it here.

Microsoft also provides [prerelease antimalware definitions](https://www.microsoft.com/en-us/wdsi/definitions/prerelease-antimalware-definitions). With these updated pattern (version 1.271.245.0) none of the installer files are classified as malware any longer. Therefore it seems that this false positive has been fixed now.

**Comment by larskanis** [comment] 2018-08-10 11:44
Next releases of RubyInstaller will be signed by an official Microsoft trusted certificate of me. Although this is not a proof by itself to be free of viruses, it creates some confidence that is taken into account by AV scanners. See here for reference: https://github.com/oneclick/rubyinstaller/issues/273#issuecomment-110567652

**Comment by luislavena** [comment] 2018-08-31 08:15
> Next releases of RubyInstaller will be signed by an official Microsoft trusted certificate of me.

@larskanis this is great to hear!, Looking forward if you can document the process of obtaining it in the projects or the contacts required for someone else that might join or step up to help with the project in the future.

As always, great work!
❤️ ❤️ ❤️

**Comment by larskanis** [comment] 2020-09-05 06:29
RubyInstaller releases are signed since two years and the issues above are gone.

**Closed by larskanis** 2020-09-05 06:29 UTC
