### ISSUE TITLE
Can we have *.chm doc files back?

### ISSUE THREAD

**Issue by IgorJorobus** [oneclick/rubyinstaller2#127] opened 2018-08-29 22:28 UTC
## Feature request

I don't know the reason why *.chm doc files stopped coming after the installers for 2.3. They were very useful, much more than the online documentation, which is harder to navigate. I would love to know the reason, and if we can have this back. Thanks in advance.

**Comment by MSP-Greg** [comment] 2018-08-29 22:42
Not really a substitute for chm, but you might try https://msp-greg.github.io/

It's a highly modified YARD doc site I created after I got tired of using RDoc or YARD with a tablet.

**Comment by larskanis** [comment] 2018-08-30 16:36
@IgorJorobus The CHM files are no longer available because the corresponding project is unmaintained and it can not be used with more recent ruby versions. Should [this issue](https://github.com/vertiginous/rdoc_chm/issues/7) become fixed, we could include CHM again.

However RubyInstaller-2.4 and up still include HTML based searchable offline docs of ruby core and stdlib. This is meant as the replacement of the former CHM files. Have a look into the start menu! It should contain a link to the offline docs.

@MSP-Greg Will your modifications be merged upstream? Is the generated doc better suited for RubyInstaller than the current RDoc based one?

**Comment by MSP-Greg** [comment] 2018-08-30 16:44
@larskanis

> Will your modifications be merged upstream?

They're a big change to YARD, and the code requires a web server.  So, probably not.

I mentioned them simply because they're another web based option for Ruby doc.

FYI, I'm using OpenSSL 1.1.1 in ruby-loco (trunk), and all is fine.  Don't know if you've considered releasing 2.6 with 1.1.1...

**Comment by larskanis** [comment] 2018-08-30 18:03
@MSP-Greg I'll upgrade rubyinstaller-2.5 and rubyinstaller-2.6 to OpenSSL-1.1.1 as soon as it's stable. Rubyinstaller-2.4 will stay on OpenSSL-1.0.2.

**Comment by MSP-Greg** [comment] 2018-08-30 18:45
Sounds good.  My code for 1.1.1 master is [here](https://github.com/MSP-Greg/ruby-makepkg-mingw/tree/master/mingw-w64-openssl-master).  Re-aligned patches, etc.  I do have a patch for the date, which won't been needed when released.

I haven't tested 1.1.1 with Ruby OpenSSL 2.1.0, but it should build. Some tests were revised...

Lastly, MSYS2/MinGW is up to GDBM 1.1.8 now.

Thanks again for your work with RI2, Greg

**Comment by larskanis** [comment] 2019-01-08 09:05
As already said the issue is, that CHM generation doesn't work with newer ruby and rdoc versions. The related issue is here: https://github.com/vertiginous/rdoc_chm/issues/7

We now have the HTML documentation as a replacement, so I'm closing this.

**Closed by larskanis** 2019-01-08 09:05 UTC
