### ISSUE TITLE
x64-msvcrt-ruby240.dll depends on libgmp-10.dll

### ISSUE THREAD

**Issue by QiWei** [oneclick/rubyinstaller2#32] opened 2017-04-18 09:57 UTC
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
x64-msvcrt-ruby230.dll does not depend on libgmp-10.dll
In addition to the system comes with no other dll files.
x64-msvcrt-ruby240.dll could dose not depends libgmp-10.dll?

**Comment by larskanis** [comment] 2017-04-18 10:10
Sorry, I don't understand your issue.

**Comment by larskanis** [comment] 2017-04-18 10:17
RubyInstaller-2.4 is compiled with libgmp support. That's why the DLL is shipped. I believe ruby can be compiled without libgmp support, but I don't plan to do so.

**Comment by QiWei** [comment] 2017-04-18 13:04
I mean static compile with libgmp.

**Comment by larskanis** [comment] 2017-04-18 14:48
Why should we static link libgmp?

**Comment by larskanis** [comment] 2017-04-20 07:51
I'm going to close the issue. Please reopen, if the issue is still relevant for you!

**Closed by larskanis** 2017-04-20 07:51 UTC
