### ISSUE TITLE
eyaml installation - undefined method `dependencies' 

### ISSUE THREAD

**Issue by MiPi12** [oneclick/rubyinstaller2#277] opened 2022-04-26 09:47 UTC
Hi, I have an issue with eyaml.
I followed the description here.

1. Install Ruby to make gem package installer available, see https://www.ruby-lang.org/en/downloads/
Without msys2 option selected (not needed here)
2. Install eyaml tool via command line: "gem install hiera-eyaml", see https://github.com/voxpupuli/hiera-eyaml
3. Verify if eyaml tool works via command line "eyaml --help"

After i type in the eyaml --help command, I get the following error:

C:/Ruby31/lib/ruby/gems/3.1.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:37:in `block (2 levels) in find': undefined method `dependencies' for #<Gem::StubSpecification:0x063e1ce0 @extension_dir=nil, @full_gem_path=nil, @gem_dir=nil, @ignored=nil, @loaded_from="C:/Ruby31/lib/ruby/gems/3.1.0/specifications/default/abbrev-0.1.0.gemspec", @data=#<Gem::StubSpecification::StubLine:0x063e163c @name="abbrev", @version=#<Gem::Version "0.1.0">, @platform="ruby", @extensions=[], @full_name="abbrev-0.1.0", @require_paths=["lib"]>, @name=nil, @spec=nil, @base_dir="C:/Ruby31/lib/ruby/gems/3.1.0", @gems_dir="C:/Ruby31/lib/ruby/gems/3.1.0/gems", @default_gem=true> (NoMethodError)

dependency = spec.dependencies.find { |d| d.name == "hiera-eyaml" }
^^^^^^^^^^^^^
from C:/Ruby31/lib/ruby/gems/3.1.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:34:in `each'
from C:/Ruby31/lib/ruby/gems/3.1.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:34:in `block in find'
from C:/Ruby31/lib/ruby/gems/3.1.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:31:in `each'
from C:/Ruby31/lib/ruby/gems/3.1.0/gems/hiera-eyaml-3.2.2/lib/hiera/backend/eyaml/plugins.rb:31:in `find'
from C:/Ruby31/lib/ruby/gems/3.1.0/gems/hiera-eyaml-3.2.2/bin/eyaml:10:in `<top (required)>'
from C:/Ruby31/bin/eyaml:32:in `load'
from C:/Ruby31/bin/eyaml:32:in `<main>'

**Comment by mohits** [comment] 2022-04-26 14:46
@MiPi12 - this looks like the cause: https://github.com/voxpupuli/hiera-eyaml/issues/325 and is probably not isolated to RubyInstaller.

**Comment by MiPi12** [comment] 2022-05-05 10:29
@mohits Thanks a lot. Fixed my problem.

**Comment by mohits** [comment] 2022-05-05 10:30
Happy to help. Thanks for coming back, and closing the issue.

**Closed** 2022-05-05 10:29 UTC
