### ISSUE TITLE
Fail to use jekyll on Win 11

### ISSUE THREAD

**Issue by junjiag** [oneclick/rubyinstaller2#248] opened 2021-11-15 02:20 UTC
## What problems are you experiencing?
`jekyll -v` failed when after installation

## Steps to reproduce
Installation via RubyInstaller (https://jekyllrb.com/docs/installation/windows/)
Download and install a Ruby+Devkit version from RubyInstaller Downloads. Use default options for installation.
Run the ridk install step on the last stage of the installation wizard. This is needed for installing gems with native extensions. You can find additional information regarding this in the RubyInstaller Documentation
Open a new command prompt window from the start menu, so that changes to the PATH environment variable becomes effective. Install Jekyll and Bundler using gem install jekyll bundler
Check if Jekyll has been installed properly: jekyll -v (FAILED)

## What's the output from `ridk version`?
ruby:
  path: C:/Ruby30-x64
  version: 3.0.2
  platform: x64-mingw32
  cc: gcc.exe (Rev5, Built by MSYS2 project) 10.3.0
ruby_installer:
  package_version: 3.0.2-1
  git_commit: 80c9ca9
msys2:
  path: C:\msys64
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.22000.318]

**Comment by MSP-Greg** [comment] 2021-11-15 02:47
One of Jekyll's 'indirect' dependencies is EventMachine.  That gem cannot be normally installed on Windows Ruby 3.0 due to a problem with the most recent EventMachine release.  You may be able to install it from the GitHub repo, or I could provide a gem that could be downloaded and installed locally.

This isn't a RubyInstaller2 issue...

**Comment by junjiag** [comment] 2021-11-15 04:42
Can you please provide me the gem which is available for Jekyll installation?

**Comment by larskanis** [comment] 2021-11-27 11:46
@junjiag You need to post the commands and the outputs in order to get any useful help. Is jekyll still a problem?

**Comment by mohits** [comment] 2021-12-17 06:55
Hi @larskanis - here is what I tried on Windows 10 because I do not have Windows 11 yet. Some lines are removed from the jeyll install for brevity.

```
$ ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]

$ gem install jekyll
Fetching unicode-display_width-1.8.0.gem
Fetching terminal-table-2.0.0.gem
...
Successfully installed sassc-2.4.0-x64-mingw32
Successfully installed jekyll-sass-converter-2.1.0
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed http_parser.rb-0.8.0
Successfully installed eventmachine-1.2.7-x64-mingw32
...
Parsing documentation for http_parser.rb-0.8.0
unknown encoding name "chunked\r\n\r\n25" for ext/ruby_http_parser/vendor/http-parser-java/tools/parse_tests.rb, skipping
Installing ri documentation for http_parser.rb-0.8.0
Parsing documentation for eventmachine-1.2.7-x64-mingw32
...
Done installing documentation for unicode-display_width, terminal-table, safe_yaml, rouge, forwardable-extended, pathutil, mercenary, liquid, kramdown, kramdown-parser-gfm, rb-inotify, rb-fsevent, listen, jekyll-watch, sassc, jekyll-sass-converter, http_parser.rb, eventmachine, em-websocket, colorator, jekyll after 30 seconds
21 gems installed
```

Thereafter, I was able to do:

```
$ jekyll -v
jekyll 4.2.1
```

Since we have no feedback from @junjiag on this, I would recommend we keep it open for a few more days to see if anyone replies, especially if they have Windows 11 (though I think the issue is not really related to Windows 11) and if we don't hear back, we close this.

**Comment by larskanis** [comment] 2021-12-25 09:41
Thank you @mohits  for trying this out! Closing now.

**Closed by larskanis** 2021-12-25 09:41 UTC
