### ISSUE TITLE
error when install gem pg_query

### ISSUE THREAD

**Issue by vnluc** [oneclick/rubyinstaller2#74] opened 2017-09-01 03:39 UTC
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
can not install gem pg_query

## Steps to reproduce
gem install pg_query    

## What's the output from `ridk version`?
D:\>ridk version
---
ruby:
  path: D:/ruby/ruby_packages_nobk/rubyinstaller-2.5.0-snapshot-x64_aug29
  version: 2.5.0
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.0-snapshot
  git_commit: 1fd689f
msys2:
  path: D:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 7.1.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]

##D:\>ruby -v
ruby 2.5.0dev (2017-08-26 trunk 59659) [x64-mingw32]

## output
D:\>gem install pg_query
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing pg_query:
        ERROR: Failed to build gem native extension.

    current directory: D:/ruby/ruby_packages_nobk/rubyinstaller-2.5.0-snapshot-x64_aug29/lib/ruby/ge
ms/2.5.0/gems/pg_query-0.13.2/ext/pg_query
D:/ruby/ruby_packages_nobk/rubyinstaller-2.5.0-snapshot-x64_aug29/bin/ruby.exe -r ./siteconf20170901
-11092-1gnnrxi.rb extconf.rb
tar: Cannot connect to D: resolve failed
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/ruby/ruby_packages_nobk/rubyinstaller-2.5.0-snapshot-x64_aug29/bin/$(RUBY_BASE_NAM
E)
extconf.rb:22:in `<main>': ERROR (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in D:/ruby/ruby_packages_nobk/rubyinstaller-2.5.0-snapshot-x64_aug29
/lib/ruby/gems/2.5.0/gems/pg_query-0.13.2 for inspection.
Results logged to D:/ruby/ruby_packages_nobk/rubyinstaller-2.5.0-snapshot-x64_aug29/lib/ruby/gems/2.
5.0/extensions/x64-mingw32/2.5.0/pg_query-0.13.2/gem_make.out

**Comment by MSP-Greg** [comment] 2017-09-01 04:25
@vnluc 

I think the issue is in the gem's extconf.rb file.  I got a similar error `tar: Cannot connect to D: resolve failed` using tar from the command line.

See https://github.com/lfittl/pg_query/issues/60#issuecomment-326483582.

**Comment by larskanis** [comment] 2017-12-29 22:13
This issue is handled [at this pg_query issue](https://github.com/lfittl/pg_query/issues/60), so that I close this one now. Thanks for your contributions!

**Closed by larskanis** 2017-12-29 22:13 UTC
